pipeline {
    agent any
    stages {
        stage('Cleanup Workspace'){
            steps{
                // Deletes all files and directories in the workspace
                sh 'rm -rf *'
            }
        }
        stage('Clone Django repo')
        {
            steps {
                sh 'git clone https://github.com/shreys7/django-todo.git'
            }
        }
        stage('Build')
        {
            steps {
                // Build Docker image
                sh 'docker build -t my_django_app:${BUILD_NUMBER} .'
            }
        }
        stage('Push docker image to docker hub')
        {
            steps {
                withCredentials([usernamePassword(credentialsId: '9b9109bf-19dc-4f74-b527-fbc97b04966f', user: 'MY_USERNAME', pass: 'MY_PASSWORD')])
                {
                    sh 'echo $MY_PASSWORD | docker login -u $MY_USERNAME --password-stdin'
                    sh 'docker push my_django_app:${BUILD_NUMBER}'
                }
            }
        }
    }
}
