pipeline{
    agent any
    stages{
        stage('Clone Django repo')
        {
            steps{
                script{
                    sh 'git clone https://github.com/shreys7/django-todo.git'
                }
            }
        }
        stage('Build')
        {
            script{
                steps{
                    // Build Docker image
                    sh 'docker build -t my_django_app:${BUILD_NUMBER} .'
                }
            }
        }
        stage('Push docker image to docker hub')
        {
            script{
                steps{
                    withCredentials([usernamePassword(credentialsId: '9b9109bf-19dc-4f74-b527-fbc97b04966f', user: 'MY_USERNAME', pass: 'MY_PASSWORD')])
                    {
                        sh 'echo $MY_PASSWORD | docker login -u $MY_USERNAME --password-stdin'
                        sh 'docker push my_django_app:${BUILD_NUMBER}'
                    }
                }
            }
        }
    }

}