pipeline {
    agent any
    stages {
        stage('Cleanup Workspace'){
            steps{
                // Deletes all files and directories in the workspace
                sh 'rm -rf *'
            }
        }
        // stage('Clone Django Repo') {
        //     steps {
        //         script {
        //             // Check if the directory exists
        //             if (fileExists('django-todo')) {
        //                 echo "Directory 'django-todo' already exists. Cleaning it up..."
        //                 sh 'rm -rf django-todo' // Remove the directory
        //             }
        //         }
        //         // Clone the repository
        //         sh 'git clone https://github.com/shreys7/django-todo.git'
        //     }
        // }
        stage('Build')
        {
            steps {
                // Build Docker image
                sh 'docker build -t cmangamm/my_django_app:${BUILD_NUMBER} .'
            }
        }
        stage('Push docker image to docker hub')
        {
            steps {
                withCredentials([usernamePassword(credentialsId: '9b9109bf-19dc-4f74-b527-fbc97b04966f', usernameVariable: 'MY_USERNAME', passwordVariable: 'MY_PASSWORD')])
                {
                    sh 'echo $MY_PASSWORD | docker login -u $MY_USERNAME --password-stdin'
                    sh 'docker push cmangamm/my_django_app:${BUILD_NUMBER}'
                }
            }
        }
    }
}
